# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  gmail_username: Your_Username
  gmail_password: Your_Password
  secret_key_base: 7586347c10b6f8e72d1a92a3e791228c587ba5570f8a6549bae728e31041f78d0661fc8b0c1da1908a7724eec2e715981666b3222223b6bbb5e61b40e4723d13

test:
  secret_key_base: bc85a4d134ee93dd13e9dd59d73d0df269466e2c2f780a1f4ba69cd54bd84c93d6b74487445ffc61d0adda06edd38ec5f434d158182f52473506b862a5dd969b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
